### ISSUE TITLE
Speedup

### ISSUE THREAD

**Issue by kwea123** [qway/nerfmeshes#3]
How much speedup do you get using your ray AABB intersection?

How does it compare to [this work](https://github.com/facebookresearch/NSVF), which uses a similar approach?

**Comment by DomainFlag** [comment]
@kwea123 For a batch of 4096 rays and 1024 voxels to be checked, on a regular CPU it takes ∼ 1.14s to efficiently sample 128 Z-values / per relevant ray while on GPU with the likes of T80, it takes approximately ∼ 38.1ms. I see that they have their own CUDA kernel for their purposes, so I assume it should be slightly faster as they use also space subdivision (octree) to disregard low-interest regions. I advise you to do some simple benchmarking, but sampling from AABB intersection is not the main bottleneck as long as you keep the number of voxels small and rich likewise.

**Comment by kwea123** [comment]
Thanks, I have read that part in the paper. But what I'd like to know is the comparison between the AABB approach and original NeRF's coarse to fine approach. Since AABB would require ray intersection with **all** voxels, I don't know if it's really more efficient than just considering the points on the ray like NeRF (even with two times network inference).

Let's say we use 64 coarse samples, then for one ray:
Your approach: ray intersection with all voxels + fine network inference on these points
NeRF: 64 coarse network inference + fine network inference on importance sampling points

In practice I think there should be much more than 1024 voxels if you want them to be rich, and I'm unsure if it's faster than 64 coarse network inference?

**Comment by DomainFlag** [comment]
The point of AABB approach is to efficient sample and some sort-of memoize high-interest regions where the samples (non-zero weights) contribute much to the rich gradients for model optimization. Sure, having infinite amount of voxels would be perfect, but that drastically downgrade the overall performance gain without contributing much due to the subdivision of the scene (logarithmically, where 4096 voxels is more than enough) + they also use embeddings to locally encode fine-grain texture (which is a plus). NeRF uses both coarse-fine network tuning, which the problem resides in the coarse model that has to guide the fine one (out of those 64 coarse samples, more than 60% have 0 weight which make them useless = useless queries) + the scene must be learned twice (coarse guides the fine) = redundancy. In other words, where NSVF does even better, is to sort-of get rid of those useless queries to encode a high-density neighborhood which can be repeatedly and efficiently queried from (i.e. visited). In the end, it's better than NeRF for both performance-wise or quality-wise, or smth in-between.
